defmodule CaseManager.CountryCodes do
  def find_key_for_value(value, [{key, val} | _]) when val == value, do: key

  def find_key_for_value(value, [{_key, [_ | _] = nested} | tail]) do
    case find_key_for_value(value, nested) do
      nil -> find_key_for_value(value, tail)
      found -> found
    end
  end

  def find_key_for_value(value, [_ | tail]), do: find_key_for_value(value, tail)
  def find_key_for_value(_, []), do: nil

  def get_full_name(country_code) do
    needle = String.to_atom(country_code)

    find_key_for_value(needle, CaseManager.CountryCodes.get_country_codes()) || :unknown
  end

  def get_country_codes() do
    [
      Unknown: [:unknown],
      Common: [
        Afghanistan: :AF,
        Algeria: :DZ,
        Egypt: :EG,
        Eritrea: :ER,
        Ethiopia: :ET,
        Iran: :IR,
        Iraq: :IQ,
        Lebanon: :LB,
        Libya: :LY,
        Morocco: :MA,
        Nigeria: :NG,
        Pakistan: :PK,
        Palestine: :PS,
        Somalia: :SO,
        Sudan: :SD,
        "South Sudan": :SS,
        Stateless: :XX,
        Syria: :SY,
        Tunisia: :TN,
        Turkey: :TR,
        Yemen: :YE
      ],
      All: [
        "Åland Islands": :AX,
        Albania: :AL,
        "American Samoa": :AS,
        Andorra: :AD,
        Angola: :AO,
        Anguilla: :AI,
        Antarctica: :AQ,
        "Antigua and Barbuda": :AG,
        Argentina: :AR,
        Armenia: :AM,
        Aruba: :AW,
        Australia: :AU,
        Austria: :AT,
        Azerbaijan: :AZ,
        Bahamas: :BS,
        Bahrain: :BH,
        Bangladesh: :BD,
        Barbados: :BB,
        Belarus: :BY,
        Belgium: :BE,
        Belize: :BZ,
        Benin: :BJ,
        Bermuda: :BM,
        Bhutan: :BT,
        Bolivia: :BO,
        "Bosnia and Herzegovina": :BA,
        Botswana: :BW,
        "Bouvet Island": :BV,
        Brazil: :BR,
        "British Indian Ocean Territory": :IO,
        "Brunei Darussalam": :BN,
        Bulgaria: :BG,
        "Burkina Faso": :BF,
        Burundi: :BI,
        Cambodia: :KH,
        Cameroon: :CM,
        Canada: :CA,
        "Cape Verde": :CV,
        "Cayman Islands": :KY,
        "Central African Republic": :CF,
        Chad: :TD,
        Chile: :CL,
        China: :CN,
        "Christmas Island": :CX,
        "Cocos (Keeling) Islands": :CC,
        Colombia: :CO,
        Comoros: :KM,
        Congo: :CG,
        "The Democratic Republic of the Congo": :CD,
        "Cook Islands": :CK,
        "Costa Rica": :CR,
        "Cote D'Ivoire": :CI,
        Croatia: :HR,
        Cuba: :CU,
        Curaçao: :CW,
        Cyprus: :CY,
        "Czech Republic": :CZ,
        Denmark: :DK,
        Djibouti: :DJ,
        Dominica: :DM,
        "Dominican Republic": :DO,
        Ecuador: :EC,
        "El Salvador": :SV,
        "Equatorial Guinea": :GQ,
        Estonia: :EE,
        "Falkland Islands (Malvinas)": :FK,
        "Faroe Islands": :FO,
        Fiji: :FJ,
        Finland: :FI,
        France: :FR,
        "French Guiana": :GF,
        "French Polynesia": :PF,
        "French Southern Territories": :TF,
        Gabon: :GA,
        Gambia: :GM,
        Georgia: :GE,
        Germany: :DE,
        Ghana: :GH,
        Gibraltar: :GI,
        Greece: :GR,
        Greenland: :GL,
        Grenada: :GD,
        Guadeloupe: :GP,
        Guam: :GU,
        Guatemala: :GT,
        Guernsey: :GG,
        Guinea: :GN,
        "Guinea-Bissau": :GW,
        Guyana: :GY,
        Haiti: :HT,
        "Heard Island and Mcdonald Islands": :HM,
        "Vatican City": :VA,
        Honduras: :HN,
        "Hong Kong": :HK,
        Hungary: :HU,
        Iceland: :IS,
        India: :IN,
        Indonesia: :ID,
        Ireland: :IE,
        "Isle of Man": :IM,
        Israel: :IL,
        Italy: :IT,
        Jamaica: :JM,
        Japan: :JP,
        Jersey: :JE,
        Jordan: :JO,
        Kazakhstan: :KZ,
        Kenya: :KE,
        Kiribati: :KI,
        "Democratic People's Republic of Korea": :KP,
        "Republic of Korea": :KR,
        Kosovo: :XK,
        Kuwait: :KW,
        Kyrgyzstan: :KG,
        Laos: :LA,
        Latvia: :LV,
        Lesotho: :LS,
        Liberia: :LR,
        Liechtenstein: :LI,
        Lithuania: :LT,
        Luxembourg: :LU,
        Macao: :MO,
        "North-Macedonia": :MK,
        Madagascar: :MG,
        Malawi: :MW,
        Malaysia: :MY,
        Maldives: :MV,
        Mali: :ML,
        Malta: :MT,
        "Marshall Islands": :MH,
        Martinique: :MQ,
        Mauritania: :MR,
        Mauritius: :MU,
        Mayotte: :YT,
        Mexico: :MX,
        "Federated States of Micronesia": :FM,
        Moldova: :MD,
        Monaco: :MC,
        Mongolia: :MN,
        Montenegro: :ME,
        Montserrat: :MS,
        Mozambique: :MZ,
        Myanmar: :MM,
        Namibia: :NA,
        Nauru: :NR,
        Nepal: :NP,
        Netherlands: :NL,
        "Netherlands Antilles": :AN,
        "New Caledonia": :NC,
        "New Zealand": :NZ,
        Nicaragua: :NI,
        Niger: :NE,
        Niue: :NU,
        "Norfolk Island": :NF,
        "Northern Mariana Islands": :MP,
        Norway: :NO,
        Oman: :OM,
        Palau: :PW,
        Panama: :PA,
        "Papua New Guinea": :PG,
        Paraguay: :PY,
        Peru: :PE,
        Philippines: :PH,
        "Pitcairn Islands": :PN,
        Poland: :PL,
        Portugal: :PT,
        "Puerto Rico": :PR,
        Qatar: :QA,
        Reunion: :RE,
        Romania: :RO,
        Russia: :RU,
        Rwanda: :RW,
        "Saint Helena": :SH,
        "Saint Kitts and Nevis": :KN,
        "Saint Lucia": :LC,
        "Saint Pierre and Miquelon": :PM,
        "Saint Vincent and the Grenadines": :VC,
        Samoa: :WS,
        "San Marino": :SM,
        "Sao Tome and Principe": :ST,
        "Saudi Arabia": :SA,
        Senegal: :SN,
        Serbia: :RS,
        Seychelles: :SC,
        "Sierra Leone": :SL,
        Singapore: :SG,
        "Sint Maarten": :SX,
        Slovakia: :SK,
        Slovenia: :SI,
        "Solomon Islands": :SB,
        "South Africa": :ZA,
        "South Georgia and the South Sandwich Islands": :GS,
        Spain: :ES,
        "Sri Lanka": :LK,
        "South Sudan": :SS,
        Sudan: :SD,
        Surivalue: :SR,
        "Svalbard and Jan Mayen": :SJ,
        Swaziland: :SZ,
        Sweden: :SE,
        Switzerland: :CH,
        Taiwan: :TW,
        Tajikistan: :TJ,
        Tanzania: :TZ,
        Thailand: :TH,
        "Timor-Leste": :TL,
        Togo: :TG,
        Tokelau: :TK,
        Tonga: :TO,
        "Trinidad and Tobago": :TT,
        Turkmenistan: :TM,
        "Turks and Caicos Islands": :TC,
        Tuvalu: :TV,
        Uganda: :UG,
        Ukraine: :UA,
        "United Arab Emirates": :AE,
        "United Kingdom": :GB,
        "United States": :US,
        "United States Minor Outlying Islands": :UM,
        Uruguay: :UY,
        Uzbekistan: :UZ,
        Vanuatu: :VU,
        Venezuela: :VE,
        Vietnam: :VN,
        "Virgin Islands, British": :VG,
        "Virgin Islands, U.S.": :VI,
        "Wallis and Futuna": :WF,
        "Western Sahara": :EH,
        Zambia: :ZM,
        Zimbabwe: :ZW
      ]
    ]
  end
end
